Repository projectcapsule/capsule, pull requests merged in 2020-08, with the labels that each got.

#29 Adding exists requirement to avoid pruning tenant owner resources
  Makefile
  controllers/tenant_controller.go
Labels: bug

#30 Syncing Namespace annotations for Storage and Ingress classes
  api/v1alpha1/tenant_annotations.go
  controllers/tenant_controller.go
  go.mod
  go.sum
Labels: enhancement

#35 NetworkPolicy validating webhook logic was the opposite
  pkg/webhook/network_policies/validating.go
Labels: bug

#36 Enabling Capsule removal and documenting it
  Makefile
  README.md
Labels: documentation, enhancement

#37 Refactoring lint GitHub Action
  .github/workflows/lint.yml
  .github/workflows/main.yaml
Labels: enhancement

#43 Updating tenant after adding/removing Namespace
  controllers/namespace_controller.go
Labels: bug, high-priority
